webtalk_init -webtalk_dir D:/work/Arcade+Projects/atari_pokey/FPGA/Prototype/Prototype/Prototype.sim/sim_1/behav/xsim/xsim.dir/tb_POKEY_Top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  2 21:44:30 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cbeff712-7dd4-4179-ac5f-c3e8a01a024d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7cb389490f9c4457a1dfb332d44b6877" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "337" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6504343700 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "26.38_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16736_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1371268647 -regid "" -xml D:/work/Arcade+Projects/atari_pokey/FPGA/Prototype/Prototype/Prototype.sim/sim_1/behav/xsim/xsim.dir/tb_POKEY_Top_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/work/Arcade+Projects/atari_pokey/FPGA/Prototype/Prototype/Prototype.sim/sim_1/behav/xsim/xsim.dir/tb_POKEY_Top_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/work/Arcade+Projects/atari_pokey/FPGA/Prototype/Prototype/Prototype.sim/sim_1/behav/xsim/xsim.dir/tb_POKEY_Top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
